In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pyreadr
%matplotlib inline

# Import Statsmodels
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller
from statsmodels.tools.eval_measures import rmse, aic

In [19]:
raw_data = pyreadr.read_r('data.RData')     # read R data
df = raw_data[next(iter(raw_data.keys()))]  # create pandas data frame
df

,longitude,latitude,date,heure,minute,seconde,nanoseconde
rownames,,,,,,,
4103,4.0944,44.1392,20110109.0,13.0,49.0,26.0,7.127392e+10
4118,4.1949,43.7687,20110109.0,15.0,1.0,29.0,6.526186e+10
4119,4.1713,44.0176,20110109.0,15.0,1.0,29.0,7.320074e+10
4121,4.2447,44.0208,20110109.0,15.0,3.0,57.0,1.459529e+10
4127,4.2613,44.0264,20110109.0,15.0,26.0,27.0,6.824676e+10
...,...,...,...,...,...,...,...
3224308,9.9725,44.4500,20210929.0,15.0,51.0,57.0,2.764736e+08
3224332,7.8693,46.9909,20210929.0,15.0,55.0,19.0,1.615380e+08
3224338,9.9629,44.4836,20210929.0,15.0,56.0,1.0,5.067223e+08
3224356,9.9905,44.4546,20210929.0,15.0,59.0,2.0,8.787177e+08
3224402,9.9791,44.4185,20210929.0,16.0,4.0,41.0,8.359621e+08

In [20]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen

def cointegration_test(df, alpha=0.05): 
    """Perform Johanson's Cointegration Test and Report Summary"""
    out = coint_johansen(df,-1,5)
    d = {'0.90':0, '0.95':1, '0.99':2}
    traces = out.lr1
    cvts = out.cvt[:, d[str(1-alpha)]]
    def adjust(val, length= 6): return str(val).ljust(length)

    # Summary
    print('Name   ::  Test Stat > C(95%)    =>   Signif  \n', '--'*20)
    for col, trace, cvt in zip(df.columns, traces, cvts):
        print(adjust(col), ':: ', adjust(round(trace,2), 9), ">", adjust(cvt, 8), ' =>  ' , trace > cvt)

cointegration_test(df)

Name   ::  Test Stat > C(95%)    =>   Signif
 ----------------------------------------
longitude ::  713423.71 > 111.7797  =>   True
latitude ::  168079.95 > 83.9383   =>   True
date   ::  115639.13 > 60.0627   =>   True
heure  ::  73304.09  > 40.1749   =>   True
minute ::  35143.61  > 24.2761   =>   True
seconde ::  4326.9    > 12.3212   =>   True
nanoseconde ::  12.86     > 4.1296    =>   True